services:
  ml-training:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        IMAGE_TAG: ${IMAGE_TAG:-v1}

    image: california-housing-ml:${IMAGE_TAG:-v1}

    container_name: california-housing-training

    volumes:
      - ./models:/app/models
      - ./results:/app/results
      - ./mlruns:/app/mlruns

    command: python -m scripts.train

  ml-prediction:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        IMAGE_TAG: ${IMAGE_TAG:-v1}

    image: california-housing-ml:${IMAGE_TAG:-v1}

    container_name: california-housing-prediction

    ports:
      - "8000:8000"

    volumes:
      - ./models:/app/models
      - ./results:/app/results
      - ./data:/app/data

    command: uvicorn src.api:app --host 0.0.0.0 --port 8000