services:
  minio:
    image: quay.io/minio/minio:latest
    container_name: mlops-minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    volumes:
      - minio_data:/data
    command: server /data --console-address ":9001"

  ml-training:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        IMAGE_TAG: ${IMAGE_TAG:-v1}
    image: california-housing-ml:${IMAGE_TAG:-v1}
    container_name: california-housing-training
    depends_on:
      - minio
    volumes:
      - ./models:/app/models
      - ./results:/app/results
      - ./mlflow.db:/app/mlflow.db
    environment:
      MLFLOW_TRACKING_URI: sqlite:////app/mlflow.db
      MLFLOW_EXPERIMENT_NAME: california-housing-regression-minio
      MLFLOW_ARTIFACT_LOCATION: s3://mlops-artifacts/mlflow
      MLFLOW_S3_ENDPOINT_URL: http://minio:9000
      AWS_ACCESS_KEY_ID: minioadmin
      AWS_SECRET_ACCESS_KEY: minioadmin
      AWS_DEFAULT_REGION: us-east-1
    command: python -m scripts.train

  ml-prediction:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        IMAGE_TAG: ${IMAGE_TAG:-v1}
    image: california-housing-ml:${IMAGE_TAG:-v1}
    container_name: california-housing-prediction
    depends_on:
      - ml-training
    ports:
      - "8000:8000"
    volumes:
      - ./models:/app/models
      - ./results:/app/results
      - ./data:/app/data
    command: uvicorn src.api:app --host 0.0.0.0 --port 8000

volumes:
  minio_data: